apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: ui-apicurio-registry
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: ui-apicurio-registry
    app.kubernetes.io/part-of: apicurio-registry
  name: ui-apicurio-registry
spec:
  ports:
  - name: "3001"
    port: 3001
    targetPort: 3001
  selector:
    app.kubernetes.io/instance: ui-apicurio-registry
status:
  loadBalancer: {}
